### ISSUE TITLE
Exact value from textbox query?

### ISSUE THREAD

**Issue by PJanisio** [no81no/jplist-php-mysql#11]
Hello, 

It is not an issue, rather a question because I cant not find solution and debugging is very tricky :)

Im curious about possibility to change query in textbox field.
I would like to find exact value and to not use LIKE statement:

``` php
case ".kupon":{
                    $result->query = " coupon_off like ? ";
                    break;
```

Is this possible?
Thank you upfront!

**Comment by 1rosehip** [comment]
I guess you can use **=** instead of **like**: 
`
$result->query = " coupon_off = ? "
`

**Comment by PJanisio** [comment]
Yeah, now after last commits I can do it. Closing. Thanks.
