### ISSUE TITLE
JPLIST Single box for title and description search

### ISSUE THREAD

**Issue by 1rosehip** [no81no/jplist-php-mysql#13]
_From @shariq619 on March 19, 2016 10:13_

I want a single box to search for both title and description in jplist php mysql 

```
                    <div class="text-filter-box">

                        <!--[if lt IE 10]>
                        <div class="jplist-label">Filter by Title:</div>
                        <![endif]-->

                        <input 
                            data-path=".title, .desc" 
                            data-button="#title-search-button"
                            type="text" 
                            value="" 
                            placeholder="Filter by Title" 
                            data-control-type="textbox" 
                            data-control-name="title-filter" 
                            data-control-action="filter"
                        />

                        <button 
                            type="button" 
                            id="title-search-button">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
```

Something like this

_Copied from original issue: no81no/jplist#177_

**Comment by 1rosehip** [comment]
_From @shariq619 on March 21, 2016 4:59_

![php mysql and html demo jplist jquery data grid controls](https://cloud.githubusercontent.com/assets/15646752/13910919/8ed49d00-ef4b-11e5-83b8-2f38b182e598.png)

**Comment by 1rosehip** [comment]
_From @shariq619 on March 21, 2016 4:59_

Is any one to help?

**Comment by 1rosehip** [comment]
_From @PJanisio on April 13, 2016 19:55_

Im curious also why this is not working in php and mysql. Tested today and no effects.

@shariq619 
did you found a solution?

Related with.
#67

**Comment by 1rosehip** [comment]
To achieve it the following control should be changed:
https://github.com/no81no/jplist-php-mysql/blob/master/server/controls/textbox.php

 For example,
$result->query = " (title like ? or  description like ?) ";

**Comment by PJanisio** [comment]
@no81no 

Does not work :(

$result->query = " (title like ? or description like ?) ";

but with one field:

$result->query = " title like ? ";

works great

**Comment by PJanisio** [comment]
OK figured it out.

Should be: 

$result->query = " (title or description like ?) ";

**Comment by 1rosehip** [comment]
Great 👍

**Comment by shariq619** [comment]
Thanks :+1:

**Comment by shariq619** [comment]
Now just description  working.

**Comment by shariq619** [comment]
In filtering.php

try this.

//get query parts, for example: 'title like ?'
            //$this->queryParts = $this->getQueryParts();

```
        //get query parts, for example: 'title like ?' ShariQ
        $this->queryParts = $this->getQueryParts();
        if(sizeof($this->queryParts)>0 && in_array(' title like ? ', $this->queryParts)){
            array_push($this->queryParts,' description like ? ');
            array_push($this->preparedParams,$this->preparedParams[0]);
        }
```

And below further

if(count($this->queryParts) > 0){       

```
            if (in_array(" title like ? ", $this->queryParts)){
                    $query .= "  join(" or ", $this->queryParts);   
                }else{
                    $query .= " join(" and ", $this->queryParts);
                }




        }
```

**Comment by tomasbohdalek** [comment]
This not working, when you have set another filters.

**Comment by tomasbohdalek** [comment]
I have solution. :) It´s easy `concat(title, description) like ?`
