### ISSUE TITLE
Range slider for php mysql

### ISSUE THREAD

**Issue by 1rosehip** [no81no/jplist-php-mysql#16]
_From @PJanisio on February 24, 2016 22:12_

Hello, 

I would like to use jquery UI range slider, it works on clean HTML site filtering by html elements. But i have no idea how to set it together with php and mysql.
I have chosen checkboxgroupfilter.php because I can set control-name there.

Created new function:

function rangeslider($status){
named it, and set-up query column.

setted up my index.html controls, but nothing changes. I have doubts if it works with dynamic data or only with static html.

_Copied from original issue: no81no/jplist#172_

**Comment by 1rosehip** [comment]
Added range slider control and demo page:
https://github.com/no81no/jplist-php-mysql/blob/master/5-range-slider.html
https://github.com/no81no/jplist-php-mysql/blob/master/server/controls/range-slider.php

**Comment by PJanisio** [comment]
@no81no 
Awesome work!

Can you please look at counter controls? Issue #10 .
Appreciate your work, is there a possibility to donate this project?

**Comment by 1rosehip** [comment]
Thank you for the feedback. I'm working on counters control now. It may take a bit more time, because it requires some javascript changes, not only php side (for every counter there should be additional select / count query that should be returned to the client side and handled by the script somehow). 

If you want to support the project, you are welcome to do it here:
https://github.com/no81no/jplist#donation
Thank you

**Comment by PJanisio** [comment]
Yeah, I saw the temp directory. Counters seems to be an easy job, but as you written all filters has to be taken into consideration.

Keeping fingers crossed. Keep going!

P.S
Donated :)

**Comment by 1rosehip** [comment]
Thank you, I appreciate your help.
