### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by universe416** [no81no/jplist-php-mysql#18]
Hello..I made changes to the jplist.demo-pages.min.css file, such as changing the font color from red to blue.  When I view the html page on my local machine, the color changes are successful; however, when I put the files on my server, the original font color (red) is still showing.  I'd appreciate any insight you can provide.  By the way, great plugin!  I plan to donate as soon as I get this portfolio page done.  Thanks.

**Comment by 1rosehip** [comment]
Hi,
Maybe it's one of the following options:
- the file is not uploaded to server
- it's your server / browser cache
- you point to the jplist CDN and not to the local file on mistake

I hope it helps :)

**Comment by universe416** [comment]
Thanks for the quick reply! The correct file is def on the server, positive the browser isn't caching the local site; I think its pointing to the plist CDN.  Can you please tell me where to change this and exactly what to change?  Thank you for your assistance.

**Comment by 1rosehip** [comment]
If you have links like this:
`<link href="//cdnjs.cloudflare.com/ajax/libs/jplist/5.2.0/css/jplist.core.min.css" rel="stylesheet" type="text/css" />`

You should change them to your local files, for example:
`<link href="/my-folder/my-file.css" rel="stylesheet" type="text/css" />`

**Comment by universe416** [comment]
What you just wrote is not appearing on the screen :(

**Comment by universe416** [comment]
Are you referring to the font library link "http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" in the html file?

**Comment by 1rosehip** [comment]
Can you send a link to your page?

**Comment by universe416** [comment]
Its set to deny all ip addresses except for mine.  In your previous message, the links you are referring to did not appear on the screen.  If you can contact me through a private message I'm happy to give you access.

**Comment by 1rosehip** [comment]
Sorry, I've updated the comment ))

**Comment by universe416** [comment]
Thanks :) - The only links in the html file are for the font libraries are they are as follows:
http://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css
http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet
(I took out some quotes to they links would appear in this message)

Maybe I should add that, I originally saved a demo as a webpage from jplist.com and have since modified it to my liking.  Not sure if that plays a role in this issue.

**Comment by 1rosehip** [comment]
It's better if you try to recreate this page from scratch without saving it from jplist.com. And then you have chances to find the issue.

**Comment by universe416** [comment]
I don't see why that should matter..like I said, I changed the font color in the demo-pages css file the changes reflect fine when I view the page on my local machine, but then when I upload it to the server, they go back to red.  If you can send me a private message, I will put the page on a different server and send you to link to view.

**Comment by 1rosehip** [comment]
You can send me your demo to no81no@gmail.com.
