### ISSUE TITLE
range-slider-toggle-filter PHP Control

### ISSUE THREAD

**Issue by 1rosehip** [no81no/jplist-php-mysql#9]
_From @shivamnetwork on February 26, 2015 7:27_

Can you please help me to code range-slider-toggle-filter via PHP MYSQL

_Copied from original issue: no81no/jplist#69_

**Comment by ghost** [comment]
I will be grateful if you add this feature in the PHP and MySQL Data Source too.

**Comment by 1rosehip** [comment]
Added control and demo page:
https://github.com/no81no/jplist-php-mysql/blob/master/6-range-toggle-filter.html
https://github.com/no81no/jplist-php-mysql/blob/master/server/controls/range-filter.php
